
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Mon May 05 23:06:48 EDT 2008
//----------------------------------------------------

package compiler.syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 54;
  public static final int GTEQ = 50;
  public static final int LSBRK = 46;
  public static final int LBRC = 33;
  public static final int LTEQ = 49;
  public static final int MODEQ = 43;
  public static final int NUM_PARTS = 24;
  public static final int TIMESEQ = 39;
  public static final int ME = 28;
  public static final int SEMI = 35;
  public static final int LPREN = 36;
  public static final int NUM_ACTIONS = 25;
  public static final int INT = 15;
  public static final int MINUS = 52;
  public static final int RANDI = 26;
  public static final int RANDF = 27;
  public static final int NOT = 62;
  public static final int AND = 58;
  public static final int LT = 60;
  public static final int OR = 59;
  public static final int COMMA = 38;
  public static final int REQUIRED = 19;
  public static final int PLUSEQ = 42;
  public static final int MINUSEQ = 41;
  public static final int PLUS = 51;
  public static final int SIMULATION = 6;
  public static final int RSBRK = 47;
  public static final int IF = 11;
  public static final int ATTRIBUTES = 17;
  public static final int DOT = 48;
  public static final int DIVIDEEQ = 40;
  public static final int ID = 32;
  public static final int EOF = 0;
  public static final int BOOLEAN = 20;
  public static final int DECIMAL = 31;
  public static final int RETURN = 14;
  public static final int TRUE = 21;
  public static final int error = 1;
  public static final int RBRC = 34;
  public static final int RPREN = 37;
  public static final int EQEQ = 56;
  public static final int ENVIRONMENT = 3;
  public static final int MOD = 55;
  public static final int NUMBER = 30;
  public static final int GLOBAL = 7;
  public static final int ACTION = 9;
  public static final int EQ = 44;
  public static final int NAME = 2;
  public static final int TIMES = 53;
  public static final int PART = 5;
  public static final int PARTICIPANT = 4;
  public static final int ELSE = 12;
  public static final int WHILE = 13;
  public static final int DOLLAR = 45;
  public static final int FLOAT = 16;
  public static final int END = 10;
  public static final int STRING = 29;
  public static final int DEF = 18;
  public static final int NUM_STEPS = 23;
  public static final int FALSE = 22;
  public static final int GT = 61;
  public static final int NOTEQ = 57;
  public static final int STEP = 8;
}

