
//----------------------------------------------------
// The following code was generated by CUP v0.10j
// Tue Apr 01 19:23:03 EDT 2008
//----------------------------------------------------

package syntax;

/** CUP generated class containing symbol constants. */
public class sym {
  /* terminals */
  public static final int DIVIDE = 51;
  public static final int GTEQ = 47;
  public static final int LSBRK = 43;
  public static final int LBRC = 30;
  public static final int LTEQ = 46;
  public static final int MODEQ = 40;
  public static final int NUM_PARTS = 21;
  public static final int TIMESEQ = 36;
  public static final int ME = 25;
  public static final int SEMI = 32;
  public static final int LPREN = 33;
  public static final int NUM_ACTIONS = 22;
  public static final int INT = 15;
  public static final int MINUS = 49;
  public static final int RANDI = 23;
  public static final int RANDF = 24;
  public static final int NOT = 59;
  public static final int AND = 55;
  public static final int LT = 57;
  public static final int OR = 56;
  public static final int COMMA = 35;
  public static final int REQUIRED = 19;
  public static final int PLUSEQ = 39;
  public static final int MINUSEQ = 38;
  public static final int PLUS = 48;
  public static final int SIMULATION = 6;
  public static final int RSBRK = 44;
  public static final int IF = 11;
  public static final int ATTRIBUTES = 17;
  public static final int DOT = 45;
  public static final int DIVIDEEQ = 37;
  public static final int ID = 29;
  public static final int EOF = 0;
  public static final int DECIMAL = 28;
  public static final int RETURN = 14;
  public static final int error = 1;
  public static final int RBRC = 31;
  public static final int RPREN = 34;
  public static final int EQEQ = 53;
  public static final int ENVIRONMENT = 3;
  public static final int MOD = 52;
  public static final int NUMBER = 27;
  public static final int GLOBAL = 7;
  public static final int ACTION = 9;
  public static final int EQ = 41;
  public static final int NAME = 2;
  public static final int TIMES = 50;
  public static final int PART = 5;
  public static final int PARTICIPANT = 4;
  public static final int ELSE = 12;
  public static final int WHILE = 13;
  public static final int DOLLAR = 42;
  public static final int FLOAT = 16;
  public static final int END = 10;
  public static final int STRING = 26;
  public static final int DEF = 18;
  public static final int NUM_STEPS = 20;
  public static final int GT = 58;
  public static final int NOTEQ = 54;
  public static final int STEP = 8;
}

